# Generated by Django 5.2.4 on 2025-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo_url',
            field=models.CharField(default='', verbose_name='Team Logo URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_tag',
            field=models.CharField(max_length=100, verbose_name='Team Tag'),
        ),
    ]
